---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/ci
inputs:
  - name: buildpacks-ci
  - name: buildpack
outputs:
  - name: buildpack-artifacts
run:
  path: buildpacks-ci/tasks/detect-and-upload/run.sh
params:
  RUBYGEM_MIRROR:
