#!/bin/bash

set -e

release_name="${ROOTFS_RELEASE:-cflinuxfs2-rootfs}"

release_dir=cflinuxfs2-rootfs-release
#filename=`cat cflinuxfs2-rootfs-release/config/blobs.yml | grep cflinuxfs2 | cut -d ':' -f 1`
filename="rootfs-nc/cflinuxfs2_nc-0.1.0-rc.*.tar.gz"

mkdir -p $release_dir/blobs/$(dirname $filename)
cp stack-s3/*.tar.gz $release_dir/blobs/$filename

pushd $release_dir
    bosh create release --force --with-tarball --name $ROOTFS_RELEASE --version 212.0.`date +"%s"`
popd

rsync -a $release_dir/ ${release_dir}-artifacts
